/*
 * Dyspatch API
 * # Introduction  The Dyspatch API is based on the REST paradigm and features resource based URLs with standard HTTP response codes to indicate errors. We use standard HTTP authentication and request verbs and all responses are JSON formatted. See our [Implementation Guide](https://docs.dyspatch.io/development/implementing_dyspatch/) for more details on how to implement Dyspatch.
 *
 * OpenAPI spec version: 2019.10
 * Contact: support@dyspatch.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'dyspatch-client/CompiledRead'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CompiledRead'));
  } else {
    // Browser globals (root is window)
    if (!root.DyspatchClient) {
      root.DyspatchClient = {};
    }
    root.DyspatchClient.LocalizationRead = factory(root.DyspatchClient.ApiClient, root.DyspatchClient.CompiledRead);
  }
}(this, function(ApiClient, CompiledRead) {
  'use strict';

  /**
   * The LocalizationRead model module.
   * @module dyspatch-client/LocalizationRead
   * @version 3.0.1
   */

  /**
   * Constructs a new <code>LocalizationRead</code>.
   * @alias module:dyspatch-client/LocalizationRead
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>LocalizationRead</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:dyspatch-client/LocalizationRead} obj Optional instance to populate.
   * @return {module:dyspatch-client/LocalizationRead} The populated <code>LocalizationRead</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('language'))
        obj.language = ApiClient.convertToType(data['language'], 'String');
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
      if (data.hasOwnProperty('template'))
        obj.template = ApiClient.convertToType(data['template'], 'String');
      if (data.hasOwnProperty('compiled'))
        obj.compiled = CompiledRead.constructFromObject(data['compiled']);
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'Date');
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'Date');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
    }
    return obj;
  }

  /**
   * An opaque, unique identifier for a localization
   * @member {String} id
   */
  exports.prototype.id = undefined;

  /**
   * A language identifier comprised of a language and a country identifier.  See [supported languages](https://docs.dyspatch.io/localization/supported_languages/). 
   * @member {String} language
   */
  exports.prototype.language = undefined;

  /**
   * The API url for a specific localization
   * @member {String} url
   */
  exports.prototype.url = undefined;

  /**
   * An opaque, unique identifier for a template
   * @member {String} template
   */
  exports.prototype.template = undefined;

  /**
   * @member {module:dyspatch-client/CompiledRead} compiled
   */
  exports.prototype.compiled = undefined;

  /**
   * The time of initial creation
   * @member {Date} createdAt
   */
  exports.prototype.createdAt = undefined;

  /**
   * The time of last update
   * @member {Date} updatedAt
   */
  exports.prototype.updatedAt = undefined;

  /**
   * The user-specified name of a localization
   * @member {String} name
   */
  exports.prototype.name = undefined;

  return exports;

}));
