/**
 * Dyspatch API
 * # Introduction  The Dyspatch API is based on the REST paradigm, and features resource based URLs with standard HTTP response codes to indicate errors. We use standard HTTP authentication and request verbs, and all responses are JSON formatted. See our [Implementation Guide](https://docs.dyspatch.io/development/implementing_dyspatch/) for more details on how to implement Dyspatch.  ## API Client Libraries Dyspatch provides API Clients for popular languages and web frameworks.  - [Java](https://github.com/getdyspatch/dyspatch-java) - [Javascript](https://github.com/getdyspatch/dyspatch-javascript) - [Python](https://github.com/getdyspatch/dyspatch-python) - [C#](https://github.com/getdyspatch/dyspatch-dotnet) - [Go](https://github.com/getdyspatch/dyspatch-golang) - [Ruby](https://github.com/getdyspatch/dyspatch-ruby) 
 *
 * The version of the OpenAPI document: 2020.11
 * Contact: support@dyspatch.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LocalizationMetaRead model module.
 * @module dyspatch-client/LocalizationMetaRead
 * @version 6.0.0
 */
class LocalizationMetaRead {
    /**
     * Constructs a new <code>LocalizationMetaRead</code>.
     * localization metadata
     * @alias module:dyspatch-client/LocalizationMetaRead
     */
    constructor() { 
        
        LocalizationMetaRead.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LocalizationMetaRead</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:dyspatch-client/LocalizationMetaRead} obj Optional instance to populate.
     * @return {module:dyspatch-client/LocalizationMetaRead} The populated <code>LocalizationMetaRead</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LocalizationMetaRead();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('localeGroup')) {
                obj['localeGroup'] = ApiClient.convertToType(data['localeGroup'], 'String');
            }
            if (data.hasOwnProperty('languages')) {
                obj['languages'] = ApiClient.convertToType(data['languages'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * An opaque, unique identifier for a localization
 * @member {String} id
 */
LocalizationMetaRead.prototype['id'] = undefined;

/**
 * The user-specified name of a localization
 * @member {String} name
 */
LocalizationMetaRead.prototype['name'] = undefined;

/**
 * The API url for a specific localization
 * @member {String} url
 */
LocalizationMetaRead.prototype['url'] = undefined;

/**
 * the locale group this localization belongs to, if this field is empty the localization does not belong to any locale group
 * @member {String} localeGroup
 */
LocalizationMetaRead.prototype['localeGroup'] = undefined;

/**
 * a list of locale codes that are available in the localization. See [supported languages](https://docs.dyspatch.io/localization/supported_languages/) for an exhaustive list of locale codes. 
 * @member {Array.<String>} languages
 */
LocalizationMetaRead.prototype['languages'] = undefined;






export default LocalizationMetaRead;

